### ISSUE TITLE
Foreign keys should be of type integer not string

### ISSUE THREAD

**Issue by thwpike** [crossroads/vend-sync#3]
Currently foreign keys are set to type `string` rather than `integer` (see https://github.com/crossroads/vend-sync/blob/5a8aa96ab0d74483a22db3ec40456d69fc923c35/lib/vend/sync/import.rb#L70-71)

**Comment by warp** [comment]
Most of the keys used by vend are guid rather than ```integer``` so I believe ```string``` is the correct type

**Comment by steveyken** [comment]
Ok, makes sense. Perhaps we could put indexes on these columns anyway?

**Comment by warp** [comment]
We currently index all columns ending in _id

**Comment by steveyken** [comment]
That's fine. I can see them now. Thanks
